### ISSUE TITLE
Not working in version Release 1.1 build 1.1.0-15558

### ISSUE THREAD

**Issue by diegovdev** [MiguelCastillo/Brackets-FileTreeSync#2]
File tree does not sync when changing to other file.

**Comment by MiguelCastillo** [comment]
@sapeish thanks for logging this. I just tried and the tree expands.  I am running my Brackets dev environment though - Release 1.3 development build 1.3.0-0 (master 49553b361).

If you run just file tree sync, does it now work?  I wonder if there is another extension that is causing issues.

**Comment by MiguelCastillo** [comment]
fixed https://github.com/MiguelCastillo/Brackets-FileTreeSync/commit/947487701e9be183f1b21cf06aa3a364c83374a2
